# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 562565d01b450d5e4b78fe883d7a8bbb68bedbc5584b9e608b39d98980f740f245c59b5d8d17f2472e243f6cd04c0335d1670a2c7d82dc33ebbb5896da6694a5

test:
  secret_key_base: b4129ee4db2382cd8b4e94142b1eba2d8292cd4ad2ce0d7cd392e318db2973ddeb5a7ce505200fd5cfefba3a4bdcb572de45514a30d53250247a264d6a393522

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
